import pyxel
from itertools import cycle

WINDOW_WIDTH = 128
WINDOW_HEIGHT = WINDOW_WIDTH

SCREENSAVER_SPEED = 4 # Higher is slower

BUBBLE_LINE_LENGTH = 32
BUBBLE_LINE_COUNT = 32

BUBBLE_SPACING = 12
BUBBLE_SPACING_MIN = 10
BUBBLE_SPACING_MAX = 14
BUBBLE_RADIUS_MIN = 5
BUBBLE_RADIUS_MAX = 8

SCREENSAVER_ORIGIN_X = -2
SCREENSAVER_ORIGIN_Y = -32
SCREENSAVER_DX_MIN = -32
SCREENSAVER_DX_MAX = 8
SCREENSAVER_DY_MIN = -46
SCREENSAVER_DY_MAX = 32

BUBBLE_COLOR_CYCLE = cycle([
  pyxel.COLOR_RED,
  pyxel.COLOR_ORANGE,
  pyxel.COLOR_YELLOW,
  pyxel.COLOR_GREEN,
  pyxel.COLOR_CYAN,
  pyxel.COLOR_PINK,
])
