SCREENSAVER_SPEED = 4 # Higher is slower

BUBBLE_LINE_LENGTH = 32
BUBBLE_LINE_COUNT = 32

BUBBLE_SPACING = 12
BUBBLE_SPACING_MIN = 10
BUBBLE_SPACING_MAX = 18
BUBBLE_RADIUS_MIN = 5
BUBBLE_RADIUS_MAX = 8
